language: c
sudo: false

addons:
  apt:
    packages:
    - libssl-dev
    - libevent-dev
    - libexpat-dev
    - clang

jobs:
  include:
    - os: osx
      name: Clang on OS X, Amd64
      compiler: clang
      arch: amd64

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        true
    fi
script:
  - |
    if [ "$TEST_UBSAN" = "yes"  ]; then
      export CFLAGS="-DNDEBUG -g2 -O3 -fsanitize=undefined -fno-sanitize-recover"
      ./configure
    elif [ "$TEST_ASAN" = "yes" ]; then
      export CFLAGS="-DNDEBUG -g2 -O3 -fsanitize=address"
      ./configure
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ./configure --enable-debug --disable-flto --with-ssl=/usr/local/opt/openssl/
    else
      ./configure --enable-debug --disable-flto
    fi
  - make -j 2
  - make test
  - (cd testdata/clang-analysis.tdir; bash clang-analysis.test)
